create type "public"."todo_priority" as enum ('now', 'next', 'later');

create type "public"."todo_status" as enum ('done', 'in_progress', 'todo', 'icebox');

create table "public"."todos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" bigint not null,
    "name" text not null,
    "description" text,
    "external_urls" text[],
    "completed_at" timestamp with time zone,
    "status" public.todo_status,
    "priority" public.todo_priority,
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."todos" enable row level security;

CREATE UNIQUE INDEX todos_pkey ON public.todos USING btree (id);

alter table "public"."todos" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";

alter table "public"."todos" add constraint "public_todos_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."todos" validate constraint "public_todos_project_id_fkey";

CREATE TRIGGER handle_updated_at_todo BEFORE UPDATE ON public.todos FOR EACH ROW EXECUTE FUNCTION moddatetime('updated_at');
