create table "public"."logs" (
    "id" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null default now(),
    "level" text,
    "message" text,
    "service" text
);

alter table "public"."logs" enable row level security;

CREATE UNIQUE INDEX logs_pkey ON public.logs USING btree (id);

alter table "public"."logs" add constraint "logs_pkey" PRIMARY KEY using index "logs_pkey";

grant delete on table "public"."logs" to "postgres";

grant insert on table "public"."logs" to "postgres";

grant references on table "public"."logs" to "postgres";

grant select on table "public"."logs" to "postgres";

grant trigger on table "public"."logs" to "postgres";

grant truncate on table "public"."logs" to "postgres";

grant update on table "public"."logs" to "postgres";

grant delete on table "public"."logs" to "service_role";

grant insert on table "public"."logs" to "service_role";

grant references on table "public"."logs" to "service_role";

grant select on table "public"."logs" to "service_role";

grant trigger on table "public"."logs" to "service_role";

grant truncate on table "public"."logs" to "service_role";

grant update on table "public"."logs" to "service_role";
