create table "public"."slack_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" text not null,
    "rememberizer_document_id" bigint,
    "sent_at" timestamp with time zone,
    "channel_name" text
);

alter table "public"."slack_messages" enable row level security;

alter table "public"."comments" enable row level security;

alter table "public"."config" enable row level security;

alter table "public"."github_webhooks" enable row level security;

alter table "public"."linear_projects" enable row level security;

alter table "public"."linear_teams" enable row level security;

alter table "public"."linear_webhooks" enable row level security;

alter table "public"."memories" enable row level security;

alter table "public"."messages" enable row level security;

alter table "public"."projects" add column "client_emails" text;

alter table "public"."projects" add column "rememberizer_key" text;

alter table "public"."prompts" enable row level security;

alter table "public"."table_change_log" enable row level security;

grant delete on table "public"."logs" to "postgres";

grant insert on table "public"."logs" to "postgres";

grant references on table "public"."logs" to "postgres";

grant select on table "public"."logs" to "postgres";

grant trigger on table "public"."logs" to "postgres";

grant truncate on table "public"."logs" to "postgres";

grant update on table "public"."logs" to "postgres";

grant delete on table "public"."slack_messages" to "postgres";

grant insert on table "public"."slack_messages" to "postgres";

grant references on table "public"."slack_messages" to "postgres";

grant select on table "public"."slack_messages" to "postgres";

grant trigger on table "public"."slack_messages" to "postgres";

grant truncate on table "public"."slack_messages" to "postgres";

grant update on table "public"."slack_messages" to "postgres";

grant delete on table "public"."slack_messages" to "service_role";

grant insert on table "public"."slack_messages" to "service_role";

grant references on table "public"."slack_messages" to "service_role";

grant select on table "public"."slack_messages" to "service_role";

grant trigger on table "public"."slack_messages" to "service_role";

grant truncate on table "public"."slack_messages" to "service_role";

grant update on table "public"."slack_messages" to "service_role";
