create table "public"."weekly_conversations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "conversation_id" uuid not null,
    "week_of_year" text not null
);

alter table "public"."weekly_conversations" enable row level security;

CREATE UNIQUE INDEX weekly_conversations_pkey ON public.weekly_conversations USING btree (id);

alter table "public"."weekly_conversations" add constraint "weekly_conversations_pkey" PRIMARY KEY using index "weekly_conversations_pkey";

grant delete on table "public"."weekly_conversations" to "postgres";

grant insert on table "public"."weekly_conversations" to "postgres";

grant references on table "public"."weekly_conversations" to "postgres";

grant select on table "public"."weekly_conversations" to "postgres";

grant trigger on table "public"."weekly_conversations" to "postgres";

grant truncate on table "public"."weekly_conversations" to "postgres";

grant update on table "public"."weekly_conversations" to "postgres";

grant delete on table "public"."weekly_conversations" to "service_role";

grant insert on table "public"."weekly_conversations" to "service_role";

grant references on table "public"."weekly_conversations" to "service_role";

grant select on table "public"."weekly_conversations" to "service_role";

grant trigger on table "public"."weekly_conversations" to "service_role";

grant truncate on table "public"."weekly_conversations" to "service_role";

grant update on table "public"."weekly_conversations" to "service_role";
