create table "public"."weekly_conversations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "conversation_id" uuid not null,
    "week_of_year" text not null
);

alter table "public"."weekly_conversations" enable row level security;

CREATE UNIQUE INDEX weekly_conversations_pkey ON public.weekly_conversations USING btree (id);

alter table "public"."weekly_conversations" add constraint "weekly_conversations_pkey" PRIMARY KEY using index "weekly_conversations_pkey";

grant delete on table "public"."weekly_conversations" to "postgres";

grant insert on table "public"."weekly_conversations" to "postgres";

grant references on table "public"."weekly_conversations" to "postgres";

grant select on table "public"."weekly_conversations" to "postgres";

grant trigger on table "public"."weekly_conversations" to "postgres";

grant truncate on table "public"."weekly_conversations" to "postgres";

grant update on table "public"."weekly_conversations" to "postgres";

grant delete on table "public"."weekly_conversations" to "service_role";

grant insert on table "public"."weekly_conversations" to "service_role";

grant references on table "public"."weekly_conversations" to "service_role";

grant select on table "public"."weekly_conversations" to "service_role";

grant trigger on table "public"."weekly_conversations" to "service_role";

grant truncate on table "public"."weekly_conversations" to "service_role";

grant update on table "public"."weekly_conversations" to "service_role";

create table "public"."project_briefings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" uuid not null,
    "briefing" text not null,
    "weekly_conversation_id" bigint
);


alter table "public"."project_briefings" enable row level security;

CREATE UNIQUE INDEX project_briefings_pkey ON public.project_briefings USING btree (id);

alter table "public"."project_briefings" add constraint "project_briefings_pkey" PRIMARY KEY using index "project_briefings_pkey";

alter table "public"."project_briefings" add constraint "public_project_briefings_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE not valid;

alter table "public"."project_briefings" validate constraint "public_project_briefings_project_id_fkey";

alter table "public"."project_briefings" add constraint "public_project_briefings_weekly_conversation_id_fkey" FOREIGN KEY (weekly_conversation_id) REFERENCES weekly_conversations(id) ON DELETE SET NULL not valid;

alter table "public"."project_briefings" validate constraint "public_project_briefings_weekly_conversation_id_fkey";

grant delete on table "public"."project_briefings" to "authenticated";

grant insert on table "public"."project_briefings" to "authenticated";

grant references on table "public"."project_briefings" to "authenticated";

grant select on table "public"."project_briefings" to "authenticated";

grant trigger on table "public"."project_briefings" to "authenticated";

grant truncate on table "public"."project_briefings" to "authenticated";

grant update on table "public"."project_briefings" to "authenticated";

grant delete on table "public"."project_briefings" to "postgres";

grant insert on table "public"."project_briefings" to "postgres";

grant references on table "public"."project_briefings" to "postgres";

grant select on table "public"."project_briefings" to "postgres";

grant trigger on table "public"."project_briefings" to "postgres";

grant truncate on table "public"."project_briefings" to "postgres";

grant update on table "public"."project_briefings" to "postgres";

grant delete on table "public"."project_briefings" to "service_role";

grant insert on table "public"."project_briefings" to "service_role";

grant references on table "public"."project_briefings" to "service_role";

grant select on table "public"."project_briefings" to "service_role";

grant trigger on table "public"."project_briefings" to "service_role";

grant truncate on table "public"."project_briefings" to "service_role";

grant update on table "public"."project_briefings" to "service_role";
