name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
          sudo dpkg -i cloudflared.deb && 
          sudo cloudflared service install CLOUDFLARE_TUNNEL

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Host ${{ secrets.SSH_HOST }}
            Hostname ${{ secrets.SSH_HOST }}
            User dokku
            IdentityFile ~/.ssh/id_ed25519
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" > ~/.ssh/config
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git push dokku@${{ secrets.SSH_HOST }}:main:master
