name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
          sudo dpkg -i cloudflared.deb && 
          cloudflared --version
          
      - name: Set up SSH through Cloudflare Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/gh-action-key
          chmod 600 ~/.ssh/gh-action-key
          echo -e "Host dokku\n\tHostName ${{ secrets.SSH_HOST }}\n\tUser dokku\n\tIdentityFile ~/.ssh/gh-action-key\n\tProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h --access-client-id ${{ secrets.CF_ACCESS_CLIENT_ID }} --access-client-secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" > ~/.ssh/config
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git push dokku@${{ secrets.SSH_HOST }}:main:main
